### ISSUE TITLE
BUGs in list filter

### ISSUE THREAD

**Issue by Anonynz** [Diegiwg/todz#1]
Problems found:

1. When we send: `todz list --status`, it breaks like this:

```javascript
    if (args[3] && args[4].length === 0) {
                          ^

TypeError: Cannot read properties of undefined (reading 'length')
    at list (todz.js:132:28)
    at cli (todz.js:263:13)
    at todz.js:284:1
    at ModuleJob.run
    at async ModuleLoader.import
    at async loadESM
    at async handleMainPromise
```
2. When we send: `todz list --status FAKE`, it returns everything anyway.
3. When we send: `todz list --status <c or i>`, it returns all Tasks anyway.

**Comment by Diegiwg** [comment]
Thanks for reporting this annoying problem. I'll fix it soon, or you could open a PR fixing S2.
